CREATE TABLE CURATORS(
	ID SERIAL PRIMARY KEY NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	SURNAME VARCHAR(255) NOT NULL
);
INSERT INTO CURATORS (NAME, SURNAME)
VALUES 
  ('John', 'Smith'),
  ('Emma', 'Johnson'),
  ('Alexander', 'Williams'),
  ('Olivia', 'Brown'),
  ('Daniel', 'Davis');
 

ALTER TABLE DEPARTMENTS
ADD COLUMN FACULTYID INT REFERENCES FACULTIES(ID);

ALTER TABLE DEPARTMENTS
ALTER COLUMN FACULTYID SET NOT NULL;

ALTER TABLE FACULTIES
DROP COLUMN DEAN;

ALTER TABLE FACULTIES
ADD COLUMN FINANCING DECIMAL(10, 2) DEFAULT 0 NOT NULL CHECK (FINANCING >= 0);

ALTER TABLE GROUPS
DROP COLUMN RATING;

ALTER TABLE GROUPS
ADD COLUMN DEPARTMENTID INT REFERENCES DEPARTMENTS(ID);

ALTER TABLE GROUPS
ALTER COLUMN DEPARTMENTID SET NOT NULL;

CREATE TABLE GROUPSCURATORS(
	ID SERIAL PRIMARY KEY NOT NULL,
	CURATORID INT NOT NULL,
	GROUPID INT NOT NULL,
	FOREIGN KEY (CURATORID) REFERENCES CURATORS (ID),
	FOREIGN KEY (GROUPID) REFERENCES GROUPS (ID)
);
INSERT INTO GROUPSCURATORS (CURATORID, GROUPID)
VALUES
	(1, 4),
	(2, 3),
	(3, 2),
	(4, 1),
	(5, 5);

CREATE TABLE SUBJECTS(
	ID SERIAL PRIMARY KEY NOT NULL,
	NAME VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE LECTURES(
	ID SERIAL PRIMARY KEY NOT NULL,
	LECTUREROOM VARCHAR(255) NOT NULL,
	SUBJECTID INT NOT NULL,
	TEACHERID INT NOT NULL,
	FOREIGN KEY (SUBJECTID) REFERENCES SUBJECTS (ID),
	FOREIGN KEY (TEACHERID) REFERENCES TEACHERS (ID)
);

CREATE TABLE GROUPSLECTURES(
	ID SERIAL PRIMARY KEY NOT NULL,
	LECTUREID INT NOT NULL,
	GROUPID INT NOT NULL,
	FOREIGN KEY (LECTUREID) REFERENCES LECTURES (ID),
	FOREIGN KEY (GROUPID) REFERENCES GROUPS (ID)
);

INSERT INTO SUBJECTS (NAME) VALUES 
  ('Mathematics'),
  ('Physics'),
  ('Chemistry'),
  ('History'),
  ('Computer Science');
 
INSERT INTO LECTURES (LECTUREROOM, SUBJECTID, TEACHERID) VALUES
  ('A122', 1, 1), 
  ('B101', 2, 2), 
  ('C432', 3, 3),
  ('D234', 4, 4), 
  ('E500', 5, 5);
 
INSERT INTO GROUPSLECTURES (LECTUREID, GROUPID) VALUES
  (1, 4), 
  (2, 1), 
  (3, 5), 
  (4, 2), 
  (5, 3); 