--1
SELECT TEACHERS.*, GROUPS.* FROM TEACHERS
CROSS JOIN GROUPS;

--2
SELECT FACULTIES.NAME FROM DEPARTMENTS 
JOIN FACULTIES ON FACULTIES.ID = DEPARTMENTS.FACULTYID
WHERE DEPARTMENTS.FINANCING > FACULTIES.FINANCING;

--3
SELECT CURATORS.SURNAME, GROUPS.NAME FROM GROUPSCURATORS
JOIN CURATORS ON CURATORS.ID = GROUPSCURATORS.CURATORID
JOIN GROUPS ON GROUPS.ID = GROUPSCURATORS.GROUPID;

--4
SELECT TEACHERS.NAME, TEACHERS.SURNAME FROM TEACHERS
JOIN LECTURES ON LECTURES.TEACHERID = TEACHERS.ID
JOIN GROUPSLECTURES ON GROUPSLECTURES.LECTUREID = LECTURES.ID
JOIN GROUPS ON GROUPS.ID = GROUPSLECTURES.GROUPID
WHERE GROUPS.NAME = 'P107';

--5
SELECT TEACHERS.SURNAME, FACULTIES.NAME FROM LECTURES
JOIN TEACHERS ON TEACHERS.ID = LECTURES.TEACHERID
JOIN GROUPSLECTURES ON GROUPSLECTURES.LECTUREID = LECTURES.ID
JOIN GROUPS ON GROUPS.ID = GROUPSLECTURES.GROUPID
JOIN DEPARTMENTS ON DEPARTMENTS.ID = GROUPS.DEPARTMENTID
JOIN FACULTIES ON FACULTIES.ID = DEPARTMENTS.FACULTYID;

--6
SELECT DEPARTMENTS.NAME, GROUPS.NAME FROM GROUPS
JOIN DEPARTMENTS ON DEPARTMENTS.ID = GROUPS.DEPARTMENTID;

--7 
SELECT TEACHERS.NAME, SUBJECTS.NAME FROM LECTURES
JOIN TEACHERS ON TEACHERS.ID = LECTURES.TEACHERID
JOIN SUBJECTS ON SUBJECTS.ID = LECTURES.SUBJECTID
WHERE TEACHERS.NAME = 'Samantha' AND TEACHERS.SURNAME = 'Adams';

--8
SELECT DEPARTMENTS.NAME FROM GROUPSLECTURES
JOIN LECTURES ON LECTURES.ID = GROUPSLECTURES.LECTUREID
JOIN GROUPS ON GROUPS.ID = GROUPSLECTURES.GROUPID
JOIN SUBJECTS ON SUBJECTS.ID = LECTURES.SUBJECTID
JOIN DEPARTMENTS ON DEPARTMENTS.ID = GROUPS.DEPARTMENTID
WHERE SUBJECTS.NAME = 'Database Theory';

--9
SELECT GROUPS.NAME FROM GROUPS
JOIN DEPARTMENTS ON DEPARTMENTS.ID = GROUPS.DEPARTMENTID
JOIN FACULTIES ON FACULTIES.ID = DEPARTMENTS.FACULTYID
WHERE FACULTIES.NAME = 'Faculty of Computer Science';

--10
SELECT GROUPS.NAME, FACULTIES.NAME FROM GROUPS
JOIN DEPARTMENTS ON DEPARTMENTS.ID = GROUPS.DEPARTMENTID
JOIN FACULTIES ON FACULTIES.ID = DEPARTMENTS.FACULTYID
WHERE GROUPS.YEAR = '5';

--11
SELECT STRING_AGG(CONCAT(TEACHERS.NAME, ' ', TEACHERS.SURNAME), ', ') AS "TEACHER FULLNAME", SUBJECTS.NAME AS "SUBJECT", GROUPS.NAME AS "GROUP"
FROM GROUPSLECTURES
JOIN LECTURES ON LECTURES.ID = GROUPSLECTURES.LECTUREID
JOIN TEACHERS ON TEACHERS.ID = LECTURES.TEACHERID
JOIN SUBJECTS ON SUBJECTS.ID = LECTURES.SUBJECTID
JOIN GROUPS ON GROUPS.ID = GROUPSLECTURES.GROUPID
WHERE LECTURES.LECTUREROOM = 'B101'
GROUP BY SUBJECTS.NAME, GROUPS.NAME;




